# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "windicss-3.1.4" = {
      name = "windicss";
      packageName = "windicss";
      version = "3.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/windicss/-/windicss-3.1.4.tgz";
        sha512 = "3RBcANxdOy/n4dLVT8+0X409sGI+piO06ARbQ8RncxGuYgdw5Ip3hrhGIYajH67lV+tHc7xNVGxj73amOC9N0g==";
      };
    };
  };
  args = {
    name = "windicss-nix";
    packageName = "windicss-nix";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."windicss-3.1.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}